@startuml
entity New {
  name : string
  created_at : datetime
  is_active : boolean
}

entity Пользователь {
}

entity Заказ {
}

entity Товар {
}

entity КомбоБургер {
}

entity Ингредиент {

}


entity Платеж {

}

entity БанковскаяКарта {

}


entity Чек {
}

entity Корзина {
}
@enduml